require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsign"
require "user.nvimtree"
require "user.bufferline"
require "user.toggleterm"
require "user.alpha"
require "user.impatient"
require "user.telescope"
require "user.lualine"

require "user.colorscheme"
